import type { Metadata } from "next";
import { Nanum_Gothic, Playfair_Display } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "./providers";

const nanum = Nanum_Gothic({
  weight: ["400", "700", "800"],
  subsets: ["latin"],
  variable: "--font-nanum-gothic",
});

const playfair = Playfair_Display({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nanum.variable} ${playfair.variable} ${nanum.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
